
import './globals.css'
import { Inter, Poppins, Mooli } from 'next/font/google'

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],

})

const inter = Inter({ subsets: ['latin'] })
import {Providers} from "./providers";


export const metadata = {
  title: 'Evo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
        {children}
        </Providers>
        
        </body>
    </html>
  )
}



